Homework 18
NET16-Homeworks/Homework_Module32 pull request #1
Opened 2022-09-19 07:14 UTC by BFipe

В общем, я не понял каким форматом делать домашку, если только мы единожды создавали новый класс. Покажите косяки, чтобы я их поисправлял, а то сам пока делал глаз набил их пропускать.

2022-09-20 10:56 UTC, im-kborovik requested changes
Разнеси по отдельным классам задания, а то ничего не понятно.
Также убери все комменты. приложение должно быть полностью рабочим.

2022-09-20 10:56 UTC, im-kborovik commented on Homework_Module32/Homework_Module32/Program.cs
> +//void _listProcessionUniqueNames(List<string> names, int listNum)
Название метода всегда должно быть в Pascal case

2022-09-20 10:56 UTC, im-kborovik commented on Homework_Module32/Homework_Module32/Program.cs
> +//    HashSet<string> ununiqueNames = new HashSet<string>();
Не очень понимаю зачем этот хэшсэт. Я просил вывести просто уникальные имена, т.е. список должен быть просто без повторений.

2022-09-20 10:56 UTC, im-kborovik commented on Homework_Module32/Homework_Module32/NumberExtractor.cs
> +                    outputNumbers.Push(temp);
а что тебе мешает тут сразу вызывать yield?) у тебя получается двойной перебор коллекции, смысл yield теряется при этом.

2022-09-20 10:56 UTC, im-kborovik commented on Homework_Module32/Homework_Module32/NumberExtractor.cs
> +        public NumberExtractor(Stack<int> numbers)
Зачем тут стэк?

2022-09-20 10:56 UTC, im-kborovik commented on Homework_Module32/Homework_Module32/NumberExtractor.cs
> +            for (int i = 0; i < count; i++)
Всё это можно было сделать с помощью массива, просто начав перебор не с начала, а с конца.

2022-09-20 11:28 UTC, BFipe reviewed
Фиксанул

2022-09-21 14:08 UTC, im-kborovik approved these changes

2022-09-21 14:08 UTC, closed without merging